"""
Interfaces and protocols for the State Manager subsystem.
Extends the core frozen IStateManager interface.
"""

from collections.abc import Callable
from typing import Any, Protocol

# The frozen interface is imported from the main kernel interfaces
from kernel.interfaces import IStateManager

from .models import StateCategory, StateObserver
from .snapshot import StateSnapshot


class StateBackend(Protocol):
    """Abstract protocol for underlying storage implementations."""

    async def get(self, category: StateCategory, key: str) -> Any | None: ...
    async def put(self, category: StateCategory, key: str, value: Any) -> None: ...
    async def delete(self, category: StateCategory, key: str) -> None: ...
    async def list_keys(self, category: StateCategory) -> list[str]: ...
    async def clear_category(self, category: StateCategory) -> None: ...
    async def dump_all(self) -> dict[StateCategory, dict[str, Any]]: ...


class StateTransaction(Protocol):
    """Context manager for batched, atomic state mutations."""

    async def put(self, category: StateCategory, key: str, value: Any) -> None: ...
    async def delete(self, category: StateCategory, key: str) -> None: ...
    async def commit(self) -> None: ...
    async def rollback(self) -> None: ...
    async def __aenter__(self) -> "StateTransaction": ...
    async def __aexit__(self, exc_type: Any, exc_val: Any, exc_tb: Any) -> None: ...


class StateStore(IStateManager, Protocol):
    """
    The public API for the StateManager.
    Inherits the frozen IStateManager (get_state, set_state, delete_state)
    and adds extended transaction and snapshot capabilities without altering the frozen contract.
    """

    async def update_state(
        self, category: StateCategory, key: str, updater: Callable[[Any], Any]
    ) -> None: ...
    async def has_state(self, category: StateCategory, key: str) -> bool: ...
    async def list_keys(self, category: StateCategory) -> list[str]: ...

    def transaction(self) -> StateTransaction: ...

    def register_observer(self, category: StateCategory, observer: StateObserver) -> None: ...
    def unregister_observer(self, category: StateCategory, observer: StateObserver) -> None: ...

    async def create_snapshot(
        self, description: str = "", metadata: dict[str, Any] | None = None
    ) -> StateSnapshot: ...
    async def restore_snapshot(self, snapshot: StateSnapshot) -> None: ...
