"""
Lifecycle Manager Subsystem.

The definitive state machine for the Chhaya Kernel. Manages subsystem
initialization and termination via dependency-based topological sorting.
"""

import asyncio
import logging
import signal
from enum import Enum
from typing import Protocol

from event_bus.bus import EventBus
from event_bus.models import Event

from .di import DIContainer


class KernelState(Enum):
    """The overarching state of the Chhaya Kernel."""

    OFF = "off"
    INITIALIZING = "initializing"
    STARTING = "starting"
    RUNNING = "running"
    STOPPING = "stopping"
    SHUTDOWN = "shutdown"
    CRASHED = "crashed"


class HealthReport:
    """A standard report generated by subsystems indicating their readiness."""

    def __init__(self, is_healthy: bool, details: dict[str, str] | None = None) -> None:
        self.is_healthy = is_healthy
        self.details = details or {}


class KernelSubsystem(Protocol):
    """
    The interface all managed subsystems must implement to be orchestrated
    by the LifecycleManager.
    """

    @property
    def name(self) -> str:
        """Returns the unique name of the subsystem."""
        ...

    @property
    def dependencies(self) -> list[str]:
        """Returns a list of subsystem names this subsystem depends on."""
        ...

    async def initialize(self) -> None:
        """Called during the INITIALIZING phase."""
        ...

    async def start(self) -> None:
        """Called during the STARTING phase."""
        ...

    async def stop(self) -> None:
        """Called during the STOPPING phase (reverse topological order)."""
        ...

    async def shutdown(self) -> None:
        """Called during the SHUTDOWN phase (reverse topological order)."""
        ...

    async def health(self) -> HealthReport:
        """Returns the current health status of the subsystem."""
        ...

    def ready(self) -> bool:
        """Synchronous check if the subsystem is ready to accept traffic/events."""
        ...


class LifecycleError(Exception):
    """Raised when the LifecycleManager encounters an error during state transitions."""

    pass


class LifecycleManager:
    """
    The orchestrator of the Chhaya Kernel state machine.
    """

    def __init__(
        self, di_container: DIContainer, event_bus: EventBus, logger: logging.Logger | None = None
    ) -> None:
        self._di = di_container
        self._bus = event_bus
        self._logger = logger or logging.getLogger("chhaya.lifecycle_manager")

        self._state = KernelState.OFF
        self._subsystems: dict[str, KernelSubsystem] = {}
        self._ordered_subsystems: list[KernelSubsystem] = []

        self._register_signal_handlers()

    @property
    def state(self) -> KernelState:
        return self._state

    def register_subsystem(self, subsystem: KernelSubsystem) -> None:
        """Registers a subsystem to be managed by the LifecycleManager."""
        if self._state != KernelState.OFF:
            raise LifecycleError("Cannot register subsystems after boot has started.")
        if subsystem.name in self._subsystems:
            raise LifecycleError(f"Subsystem '{subsystem.name}' is already registered.")
        self._subsystems[subsystem.name] = subsystem

    def _sort_dependencies(self) -> None:
        """
        Sorts the registered subsystems topologically based on their dependencies.
        Raises LifecycleError if a circular dependency or missing dependency is detected.
        """
        visited: set[str] = set()
        temp_mark: set[str] = set()
        ordered: list[KernelSubsystem] = []

        def visit(name: str) -> None:
            if name in temp_mark:
                raise LifecycleError(f"Circular dependency detected involving subsystem '{name}'")
            if name in visited:
                return

            if name not in self._subsystems:
                raise LifecycleError(f"Missing dependency: '{name}' is not registered.")

            temp_mark.add(name)
            subsystem = self._subsystems[name]

            for dep in subsystem.dependencies:
                visit(dep)

            temp_mark.remove(name)
            visited.add(name)
            ordered.append(subsystem)

        for sub_name in self._subsystems:
            if sub_name not in visited:
                visit(sub_name)

        self._ordered_subsystems = ordered

    async def get_health(self) -> dict[str, HealthReport]:
        """Returns the aggregated health reports from all subsystems."""
        reports = {}
        for sub in self._ordered_subsystems:
            try:
                reports[sub.name] = await sub.health()
            except Exception as e:
                self._logger.error(f"Health check failed for {sub.name}: {e}")
                reports[sub.name] = HealthReport(is_healthy=False, details={"error": str(e)})
        return reports

    async def _transition(self, new_state: KernelState, event_name: str) -> None:
        self._state = new_state
        await self._bus.publish(Event(type=event_name))

    async def boot(self) -> None:
        """Executes INITIALIZING and STARTING sequences, transitioning to RUNNING."""
        if self._state != KernelState.OFF:
            raise LifecycleError(f"Cannot boot from state {self._state.value}.")

        self._sort_dependencies()

        try:
            # 1. INITIALIZING Phase
            await self._transition(KernelState.INITIALIZING, "system.state.initializing")
            for sub in self._ordered_subsystems:
                self.before_initialize(sub)
                await sub.initialize()
                self.after_initialize(sub)

            # 2. STARTING Phase
            await self._transition(KernelState.STARTING, "system.state.starting")
            for sub in self._ordered_subsystems:
                self.before_start(sub)
                await sub.start()
                self.after_start(sub)

            # 3. RUNNING Phase
            await self._transition(KernelState.RUNNING, "system.state.running")
            self._logger.info("Chhaya Kernel is now RUNNING.")

        except Exception as e:
            self._logger.critical(f"Boot failed during {self._state.value} phase: {e}")
            await self._transition(KernelState.CRASHED, "system.state.crashed")
            # Attempt graceful shutdown of what did start
            await self.shutdown(force_from_crash=True)
            raise LifecycleError(f"Boot failed: {e}") from e

    async def shutdown(self, force_from_crash: bool = False) -> None:
        """Executes STOPPING and SHUTDOWN sequences."""
        if self._state in (KernelState.SHUTDOWN, KernelState.OFF):
            return

        if not force_from_crash and self._state not in (KernelState.RUNNING, KernelState.STARTING):
            self._logger.warning(f"Shutdown called from unexpected state {self._state.value}")

        # If forced from crash, we want to remember we are crashed
        original_state = self._state
        if force_from_crash:
            original_state = KernelState.CRASHED

        try:
            # 1. STOPPING Phase (Reverse Topological Order)
            # Only publish stopping if we aren't crashed
            if not force_from_crash:
                await self._transition(KernelState.STOPPING, "system.state.stopping")
            else:
                await self._bus.publish(Event(type="system.state.stopping"))

            for sub in reversed(self._ordered_subsystems):
                try:
                    self.before_stop(sub)
                    await sub.stop()
                    self.after_stop(sub)
                except Exception as e:
                    self._logger.error(f"Error stopping subsystem {sub.name}: {e}")

            # 2. SHUTDOWN Phase (Reverse Topological Order)
            for sub in reversed(self._ordered_subsystems):
                try:
                    self.before_shutdown(sub)
                    await sub.shutdown()
                    self.after_shutdown(sub)
                except Exception as e:
                    self._logger.error(f"Error shutting down subsystem {sub.name}: {e}")

            await self._bus.publish(Event(type="system.state.shutdown"))

            if original_state == KernelState.CRASHED:
                self._state = KernelState.CRASHED
            else:
                self._state = KernelState.SHUTDOWN

            self._logger.info("Chhaya Kernel SHUTDOWN complete.")

        except Exception as e:
            self._logger.critical(f"Critical error during shutdown: {e}")
            self._state = KernelState.CRASHED
            raise LifecycleError(f"Shutdown failed: {e}") from e

    def _register_signal_handlers(self) -> None:
        """Binds to SIGINT and SIGTERM to trigger graceful shutdown."""
        try:
            loop = asyncio.get_running_loop()
        except RuntimeError:
            return  # No running event loop during init (e.g. tests)

        def handle_signal(sig: int) -> None:
            self._logger.info(f"Received signal {sig}. Initiating graceful shutdown.")
            asyncio.create_task(self.shutdown())

        for sig in (signal.SIGINT, signal.SIGTERM):
            try:
                loop.add_signal_handler(sig, handle_signal, sig)
            except NotImplementedError:
                # Windows doesn't fully support add_signal_handler
                signal.signal(sig, lambda s, f: handle_signal(s))

    # --- Lifecycle Hooks ---

    def before_initialize(self, subsystem: KernelSubsystem) -> None:
        pass

    def after_initialize(self, subsystem: KernelSubsystem) -> None:
        pass

    def before_start(self, subsystem: KernelSubsystem) -> None:
        pass

    def after_start(self, subsystem: KernelSubsystem) -> None:
        pass

    def before_stop(self, subsystem: KernelSubsystem) -> None:
        pass

    def after_stop(self, subsystem: KernelSubsystem) -> None:
        pass

    def before_shutdown(self, subsystem: KernelSubsystem) -> None:
        pass

    def after_shutdown(self, subsystem: KernelSubsystem) -> None:
        pass
